### ISSUE TITLE
why not run with Chinese when  i load urdf wth chinese by ignore?

### ISSUE THREAD

**Issue by chenwenyou** [ros/joint_state_publisher#57]
[urdf01_HelloWorld.urdf.txt](https://github.com/ros/joint_state_publisher/files/5564669/urdf01_HelloWorld.urdf.txt)

csj-wenyo@csjwenyo-ThinkPad-T490:/catkin_ws/src/robotsim/urdf/urdf$ check_urdf urdf01_HelloWorld.urdf.txt
robot name is: mycar
---------- Successfully Parsed XML ---------------
root Link: base_footprint has 1 child(ren)
child(1): base_link
child(1): back_wheel
child(2): front_wheel
child(3): left_wheel
child(4): right_wheel
csj-wenyo@csjwenyo-ThinkPad-T490:/catkin_ws/src/robotsim/urdf/urdf$

process[joint_state_publisher_gui-5]: started with pid [17029]
Traceback (most recent call last):
File "/home/csj-wenyo/catkin_ws/src/joint_state_publisher/joint_state_publisher/scripts/joint_state_publisher", line 42, in
jsp = joint_state_publisher.JointStatePublisher()
File "/opt/ros/melodic/lib/python2.7/dist-packages/joint_state_publisher/init.py", line 159, in init
robot = xml.dom.minidom.parseString(description)
File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
return expatbuilder.parseString(string)
File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
return builder.parseString(string)
File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
parser.Parse(string, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 27-28: ordinal not in range(128)
Traceback (most recent call last):
File "/home/csj-wenyo/catkin_ws/src/joint_state_publisher/joint_state_publisher_gui/scripts/joint_state_publisher_gui", line 53, in
joint_state_publisher.JointStatePublisher(),
File "/opt/ros/melodic/lib/python2.7/dist-packages/joint_state_publisher/init.py", line 159, in init
robot = xml.dom.minidom.parseString(description)
File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
return expatbuilder.parseString(string)
File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
return builder.parseString(string)
File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
parser.Parse(string, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 27-28: ordinal not in range(128)
[joint_state_publisher-4] process has died [pid 17028, exit code 1, cmd /home/csj-wenyo/catkin_ws/src/joint_state_publisher/joint_state_publisher/scripts/joint_state_publisher __name:=joint_state_publisher __log:=/home/csj-wenyo/.ros/log/83b7df5c-2a2b-11eb-8cfd-58961d963f57/joint_state_publisher-4.log].
log file: /home/csj-wenyo/.ros/log/83b7df5c-2a2b-11eb-8cfd-58961d963f57/joint_state_publisher-4*.log
[joint_state_publisher_gui-5] process has died [pid 17029, exit code 1, cmd /home/csj-wenyo/catkin_ws/src/joint_state_publisher/joint_state_publisher_gui/scripts/joint_state_publisher_gui __name:=joint_state_publisher_gui __log:=/home/csj-wenyo/.ros/log/83b7df5c-2a2b-11eb-8cfd-58961d963f57/joint_state_publisher_gui-5.log].
log file: /home/csj-wenyo/.ros/log/83b7df5c-2a2b-11eb-8cfd-58961d963f57/joint_state_publisher_gui-5*.log

**Comment by clalancette** [comment]
This should be fixed by #58.  Thanks for reporting the issue.
